//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id { get; set; }
        public string Rego { get; set; }
        public string Make { get; set; }
        public string Mode { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string Lat { get; set; }
        public string Log { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Driver { get; set; }
        public Nullable<bool> isActivy { get; set; }
    }
}
